### PR TITLE
'url' attribute should point to repository with packaging code

### PR DESCRIPTION
**Pull request by liberforce**
See https://docs.conan.io/en/latest/reference/conanfile/attributes.html#url

### CODE REVIEW

**Comment by liberforce** [comment]
Sorry, just saw I did a brown paper bag bug...

**Comment by liberforce** [comment]
Addressed in merge request #7.

**Comment by liberforce** [comment]
Seems the travis checks are not enough.

**Comment by danimtb** [comment]
uhm, seems travis job is not wokring. Will manage. Thanks

**Comment by danimtb** [comment]
Should be fixed now and available in conan-center

**Pull request merged**
